package codegraph

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// issue #140:自动生成的源码(EF Core 模型快照、protoc / go generate 产物等)按头部标记跳过,
// 不喂给 tree-sitter、不进图谱 —— 避免大型 .NET 仓把子进程顶过内存上限(exit 75)。
func TestIsGeneratedSource(t *testing.T) {
	gen := []string{
		"// <auto-generated />\npublic class Foo {}\n",                     // EF Core / .NET
		"// <auto-generated>\n//   由工具生成\n// </auto-generated>\nclass F{}", // 带换行的 .NET 头
		"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage pb\n",   // Go / protoc
		"/* @generated */\nexport const x = 1\n",                           // @generated 约定
	}
	for _, s := range gen {
		if !isGeneratedSource([]byte(s)) {
			t.Errorf("应判定为生成文件:\n%s", s)
		}
	}
	normal := []string{
		"package x\n\nfunc RealFunc() {}\n",
		"public class Service {\n  // do not edit lightly, but hand-written\n", // 注:不含 DO NOT EDIT 全大写连写
		"",
	}
	for _, s := range normal {
		if isGeneratedSource([]byte(s)) {
			t.Errorf("正常源码不该判定为生成文件:\n%q", s)
		}
	}

	// 标记在 1KB 头部之外 → 不判定(只扫头部,省时且避免误伤正文里偶然出现的字样)。
	deep := strings.Repeat("x\n", 2000) + "// <auto-generated />\n"
	if isGeneratedSource([]byte(deep)) {
		t.Error("超出头部扫描窗口的标记不应触发判定")
	}
}

// TestMigrationsDirSkipped:`Migrations/` 目录(EF Core / Django 约定)整体跳过。
func TestMigrationsDirSkipped(t *testing.T) {
	for _, n := range []string{"migrations", "Migrations", "MIGRATIONS"} {
		if !shouldSkipDir(n) {
			t.Errorf("%q 应被跳过", n)
		}
	}
}

// TestAssembleSkipsGeneratedAndMigrations:端到端验证收紧后的行为(issue #140):
//   - 手写文件入图;
//   - **大**生成文件跳过(内存元凶 + 低导航价值);
//   - **小**生成文件**保留**(常含被引用的类型定义,且不撑内存);
//   - Migrations 目录整体跳过。
func TestAssembleSkipsGeneratedAndMigrations(t *testing.T) {
	root := t.TempDir()
	mk := func(rel, content string) {
		p := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	const genHeader = "// Code generated by tool. DO NOT EDIT.\npackage x\n\n"
	// 大生成文件:头部标记 + ≥128KiB 短注释行填充(不触发超长行)+ 一个符号。
	pad := strings.Repeat("// padding line to inflate file size\n", 4000) // ~148 KiB
	mk("real.go", "package x\n\nfunc RealFunc() {}\n")                    // 手写,入图
	mk("gen_small.go", genHeader+"func GeneratedSmall() {}\n")            // 生成但小 → 保留
	mk("gen_big.go", genHeader+pad+"func GeneratedBig() {}\n")            // 生成且大 → 跳过
	mk("Migrations/mig.go", "package x\n\nfunc MigFunc() {}\n")           // Migrations 目录 → 跳过

	ix := &Index{root: root}
	g, _, err := ix.assemble(nil, false)
	if err != nil {
		t.Fatal(err)
	}
	names := map[string]bool{}
	for _, s := range g.Symbols {
		names[s.Name] = true
	}
	if !names["RealFunc"] {
		t.Error("手写文件的 RealFunc 应入图")
	}
	if !names["GeneratedSmall"] {
		t.Error("小生成文件的 GeneratedSmall 应保留入图(收紧后只跳大文件)")
	}
	if names["GeneratedBig"] {
		t.Error("大生成文件的 GeneratedBig 不该入图")
	}
	if names["MigFunc"] {
		t.Error("Migrations 目录的 MigFunc 不该入图")
	}
}
